Drawer = require "canvas.canvas"
canvas_data = require "canvas.canvas_data"

function init(self)
	self.canvas = Drawer(260, 260, "#right_sprite")
	canvas_data.right_canvas = self.canvas
end 


function update(self, dt)
	self.canvas:update(dt)
end


function on_message(self, message_id, message, sender)
	self.canvas:on_message(message_id, message, sender)
end


function on_input(self, action_id, action)
	self.canvas:on_input(action_id, action)
end


function final(self)
	self.canvas:final()
end